vib.settings:
  type: config_object
  label: View in browser processors settings.
  mapping:
    cron_job_time:
      type: string
      label: The cron job running period.
    modules:
      type: sequence
      label: List of modules.
      sequence:
        type: sequence
        label: List of keys for a given module.
        sequence:
          type: mapping
          label: Per module/key setting.
          mapping:
            lifetime:
              type: string
              label: The period of link lifetime.
            library:
              type: string
              label: The library to attach.
